### ISSUE TITLE
Crashes when saved *sometimes*

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#12]
via Windows & Mac on the latest "devel" branch.

![image](https://cloud.githubusercontent.com/assets/5713937/15865116/859f6ece-2ca7-11e6-814c-e9ec1d1f98a2.png)

**Comment by maxdee** [comment]
More details please! What does it take to reproduce the bug?

**Comment by chelsealiggatt** [comment]
The two factors that both the Windows and Mac crashes had in common was
1) long play time 2) crashes when attempting to save...

[image: Inline image 1]

On Tue, Jun 7, 2016 at 12:07 PM, maxdee <notifications@github.com> wrote:

> More details please! What does it take to reproduce the bug?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/maxdee/alc_freeliner/issues/12#issuecomment-224330071>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFcwEXl-J8wcmxIf3zfxsMK935k6Bf9Kks5qJZdXgaJpZM4IwFsx>
> .
>



-- 
Chelsea Liggatt
www.chelsealiggatt.com

**Comment by maxdee** [comment]
Is the error message the same on OSX?

**Comment by chelsealiggatt** [comment]
Here is the Windows error msg. The one I posted before was OSX! I am unsure
whether or not they're one in the same. But both errors were incurred while
saving after long play time.

On Thu, Jun 9, 2016 at 6:36 PM, maxdee <notifications@github.com> wrote:

> Is the error message the same on OSX?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/maxdee/alc_freeliner/issues/12#issuecomment-225047315>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFcwEbhym-ghzwxDYwFzJHsxiVS_NjWgks5qKJVQgaJpZM4IwFsx>
> .
>



-- 
Chelsea Liggatt
www.chelsealiggatt.com

**Comment by chelsealiggatt** [comment]
It's also possible that shaders were active during both sessions. Hopefully
this helps a little!

=D

On Thu, Jun 9, 2016 at 6:50 PM, Chelsea Liggatt <chelsealiggatt@gmail.com>
wrote:

> Here is the Windows error msg. The one I posted before was OSX! I am
> unsure whether or not they're one in the same. But both errors were
> incurred while saving after long play time.
>
> On Thu, Jun 9, 2016 at 6:36 PM, maxdee <notifications@github.com> wrote:
>
>> Is the error message the same on OSX?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/maxdee/alc_freeliner/issues/12#issuecomment-225047315>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AFcwEbhym-ghzwxDYwFzJHsxiVS_NjWgks5qKJVQgaJpZM4IwFsx>
>> .
>>
>
>
>
> --
> Chelsea Liggatt
> www.chelsealiggatt.com
>



-- 
Chelsea Liggatt
www.chelsealiggatt.com

**Comment by maxdee** [comment]
Issue seems to no longer be an issue.
