### ISSUE TITLE
Fix issue with simpleHttp library and address

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#19]
Hey, 
as discussed when at Eclipse.
While the LEDs were plugged into Enttec Led Mapper (or ELM) and FreeLiner was spouted-in... 
I'd receive this error notification. Only when I reset the computer and started FreeLiner first would it work.

Any ideas?

![img_1779](https://cloud.githubusercontent.com/assets/5713937/17833662/cd569e7a-66f1-11e6-8b1c-a31af29be1ba.JPG)

**Comment by maxdee** [comment]
This happens when two freeliner's with webserver are running at the same time. Its an issue with the simplehttp library. Thats why it works after reboot. Make sure you properly close freeliner before opening it again.
