### ISSUE TITLE
SVG files not always loading

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#20]
As previously discussed;
Although I am making all SVG files in 1pt paths that are straight edged, not curved, without fills, and with correct grouping... I am having a hard time importing even the simplest of designs. It seems kind of random to me when the SVG importation will work or not. Is there an explanation or easy resolution for this? And for the time being, is it possible to add back the background.png feature that allows users to trace a background image within FreeLiner? However, please note, that when the background.png feature is enabled, it always seems to import the background image off centre...

**Comment by maxdee** [comment]
Why is this closed?
There is the imageLayer which will let you load images, make sure you put it after a render layer though, as it needs a buffer to draw to, this isent clear and I should fix it! Someway to show if a layer needs a incoming buffer and if a layer is returning one. 
![imagelayer_screenshot](https://cloud.githubusercontent.com/assets/1138961/18560166/6cb8c78a-7b48-11e6-9b5b-cbc7f213fe00.png)

**Comment by maxdee** [comment]
If you can provide more details with the svg problem, if you can provide actual problematic files that would help also.
