### ISSUE TITLE
implement frame capture layer

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#21]
<img width="1280" alt="screen shot 2016-09-15 at 2 31 24 am" src="https://cloud.githubusercontent.com/assets/5713937/18540407/76a12096-7aec-11e6-9532-bcbbf3d3ce08.png">

Will this feature be reintroduced sometime soon? It's a very fun and useful feature for making HD .gifs!

**Comment by maxdee** [comment]
Yes its been gone for a while and needs to be re-implemented as a layer! Love me some layers. I might be able to get to that today.
