### ISSUE TITLE
[r polka: 145]  [FPS 0] 

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#24]
I reached an all time low of Frames Per Second! Yippie. 
<img width="1280" alt="screen shot 2016-09-29 at 2 30 53 am" src="https://cloud.githubusercontent.com/assets/5713937/18943251/6670ae7a-85ec-11e6-93fe-5cb698be04aa.png">

**Comment by maxdee** [comment]
This lacks information to be an issue. It might make sense that if you render things 145 times * how many times you triggered it.
