### ISSUE TITLE
Questions regarding Shaders

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#28]
1. Where is loadShader() called, what's the correct place to patch into
2. Where are the uniforms passed
3. Where is the vertex array (name?) created and passed in, the geometry
4. Where are the textures passed
Generally, how/where can GLSL shader code be connected the Processing/Java code, and controlled through the UI

**Comment by maxdee** [comment]
1. & 2. Use search this repository at the top of the github page.
3. Processing handles that.
4. Through the layer system.
