### ISSUE TITLE
Full-screen on Display 1

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#32]
![freeliner](https://user-images.githubusercontent.com/5713937/31051099-85ec25d8-a62d-11e7-9095-cea3fd8ab122.png)

**Comment by maxdee** [comment]
again use more words to describe your problem, including details that might be pertinent to the issue

**Comment by chelsealiggatt** [comment]
I believe the issue was from my computer being plugged into an external monitor without first rebooting and then restarting.
