### ISSUE TITLE
subtract action

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#36]
Is there a way to subtract a template from a geometry; 
i.e: I've added template "B" to "A" using the "add" action = ctrl-b. But now I want to subtract template "A" from "AB".

**Comment by maxdee** [comment]
we sorted this out together, closing.

**Comment by maxdee** [comment]
For clarity :
`AB` and `ctrl-b` toggles `B` for all geomtery with `A`
