### ISSUE TITLE
Processing-Video not being recognized by freeliner sketch

### ISSUE THREAD

**Issue by AcidPixels** [maxdee/alc_freeliner#41]
Hey, I've been trying out some New VJ methods, and I'm trying to install and launch alc_freeliner. The other elements I've added to the processing libraries, and they run fine. When i run the sketch it's saying that the "library not found for processing.video" I've tried renaming the folder and such but nada. Can someone help me please. Thank You.

P.S. - Complete noob to processing, I know some coding though.

**Comment by AcidPixels** [comment]
<img width="1266" alt="screen shot 2017-12-17 at 9 25 23 am" src="https://user-images.githubusercontent.com/34616523/34080450-4dc09092-e30c-11e7-96ca-6f6037ef9e2e.png">

**Comment by maxdee** [comment]
Have tried installing the video library through the Processing library
manager? In Processing click 'Sketch' then 'Add library' then 'import
library'. You may need to install GStreamer.

**Comment by maxdee** [comment]
never heard back closing
