### ISSUE TITLE
SVG import / export

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#5]
As previously discussed, the ability to import and export SVG files would greatly improve FreeLiner! 

=D

**Comment by maxdee** [comment]
Export will not be supported as there is no export svg function, I could make one but it will require more time than I can afford for this feature.
Loading has a prototype for now, with the command `geom load filename.svg` with a corresponding svg file in `data/userdata`. I pushed a commit to devel branch but i dont know why its not showing up yet...

**Comment by chelsealiggatt** [comment]
Hey,
what's the full name of the "http" library, I am having trouble searching
it via Processing.

Also,
came across the library: "Bézier Editor
<http://drifkin.net/processing/beziereditor> 1.0.0"

May be useful?


On Mon, May 23, 2016 at 1:56 PM, maxdee <notifications@github.com> wrote:

> Export will not be supported as there is no export svg function, I could
> make one but it will require more time than I can afford for this feature.
> Loading has a prototype for now, with the command geom load filename.svg
> with a corresponding svg file in data/userdata. I pushed a commit to
> devel branch but i dont know why its not showing up yet...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/maxdee/alc_freeliner/issues/5#issuecomment-221042719>
>



-- 
Chelsea Liggatt
www.chelsealiggatt.com

**Comment by maxdee** [comment]
its called simplehttp
it might not install, so download it here
http://diskordier.net/simpleHTTPServer/
