### ISSUE TITLE
Install on Windows 10 64

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [maxdee/alc_freeliner#53]
Hi,

I am trying to use freeliner for a project on sculptures.
I am on Windows 10 64.
I installed everything.
But i have the msg when i run freeliner :

> No library found for http
> Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window).
> The package “http” does not exist. You might be missing a library.

I tried to copy the files from the zip https://diskordier.net/simpleHTTPServer/ in my libraries directory but it did not work.

Any idea ?

**Comment by Jacques-Olivier-Farcy** [comment]
Found it !

Restarting Processing solved the problem. I'm in !

**Comment by maxdee** [comment]
Great!
