### ISSUE TITLE
Feature : invert the mirror display ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [maxdee/alc_freeliner#54]
When testing Freeliner, i don't use a projector.

So my screen is like a mirror, i can't read the texts messages. Is it possible to have an option to invert this ?

**Comment by maxdee** [comment]
Hmm weird, are you making lines left to right or right to left? It should be right to left for text (because scrolling text should be right to left). Otherwise send me a screenshot.

**Comment by Jacques-Olivier-Farcy** [comment]
![image](https://user-images.githubusercontent.com/19731340/52084326-1cd28880-25a2-11e9-88e2-8fcbca86d320.png)
Right to left seems better but the letters are so small

**Comment by maxdee** [comment]
Hmm yes indeed the last project I worked on needed small font :)
You can set it in `freeliner_sketch/Config` at the [line](https://github.com/maxdee/alc_freeliner/blob/5b97156b51b60685f28da0897e546d780a276a8f/freeliner_sketch/Config.pde#L39) `final int GUI_FONT_SIZE = 10;`

**Comment by Jacques-Olivier-Farcy** [comment]
![image](https://user-images.githubusercontent.com/19731340/52088714-f1a16680-25ac-11e9-985e-928ea8d6ead9.png)
Really better, My eyes thank you !

**Comment by maxdee** [comment]
Oh you are in france right? One big problem with freeliner is that it is not as intuitive to use with french azerty keyboards. I do have this in mind with the next version.

**Comment by Jacques-Olivier-Farcy** [comment]
I see, at this point i am using Web GUI, in the near futur i understand i should use an english keyboard.

And thanks to have french stuff in your mind.

Anyway, have you tried another kind of input ?
With a joystick with http://qjoypad.sourceforge.net/ for example ?
I will try things, i let you know.

**Comment by maxdee** [comment]
Anything can be used to control freeliner via the OSC command api. 
I dont want to have device specific code in freeliner, but one could make a PureData patch or a python script to connect a joystick to freeliner.

**Comment by Jacques-Olivier-Farcy** [comment]
Thank you. You can close this issue.
