### ISSUE TITLE
"FreeLiner" does not exist

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#6]
Just downloaded the latest FreeLiner via Devel branch and when I attempted to start the sketch I received this msg...
![ea8681d8-77b7-4a08-a871-cece0086ba6a](https://cloud.githubusercontent.com/assets/5713937/15515464/41a1e602-21a3-11e6-9531-d5f806eedcae.jpg)

**Comment by maxdee** [comment]
Ok I think I know what causes it, unzipping on windows. Does `alc_freeliner/freeliner_sketch/` contain many `.pde` files or just one? If it only contains `freeliner_sketch.pde`, windows sucks and cant unzip things properly. Had the issue on Jhotas machine. Your machine has git, thats how I got freeliner on there at first.
