### ISSUE TITLE
Understanding colors

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [maxdee/alc_freeliner#60]
Hello,

I am using ALC_freeliner quite a lot these days and i really enjoy creating stuff with it.

I have tested a lot of things with the WEB GUI or directly with keyboard.
I also look into the pde files.

But i can't undestand how to use my own colors.
I also wants to add effects like the millsfade one with my own colors.

I would really appreciate if you can help me on that.

I will continue to fill out the wiki pages as soon as I understand this color story.

**Comment by maxdee** [comment]
Hi I also dont really understand colors, im colorblind!
If you use the `stroke` or `fill` color dialog in the web interface, make sure to also set the stroke or fill mode for the template to `CustomColor`. You can also send commands yourself `tp stroke A #de2ac2` or in OSC `/tp/stroke/A/#de2ac2`.

There is also a system to make complex color animations, but has to do with meta freelining.

**Comment by Jacques-Olivier-Farcy** [comment]
Hello Maxdee,

Well i am not colorblind ! It should be easier for me, but i still can't have my own colors working for my template.

I am actually on Windows 10 ( my debian computer is not powerful enough).
I tried this :
![image](https://user-images.githubusercontent.com/19731340/54083045-eb767680-431e-11e9-982d-9126e7d6927c.png)

But the color to fill the geometry renderer stay black. Maybe a bug ?

**Comment by Jacques-Olivier-Farcy** [comment]
And i also tried to send a cmd with the web interface :

![image](https://user-images.githubusercontent.com/19731340/54083283-c1728380-4321-11e9-9980-60d3865f70d3.png)

And nothing is happening.

**Comment by maxdee** [comment]
Hello sorry for the delay. Did you set the `strokeMode` for `A` to `28` also know as `CustomStrokeColor`?
